#+title: Doom Emacs Config
#+author: Atri Hegde
#+startup: overview latexpreview

* Table of Contents :TOC:
- [[#general][General]]
  - [[#user-information][User Information]]
  - [[#auto-save-buffers][Auto save buffers]]
  - [[#tab-size][Tab size]]
- [[#user-interface][User Interface]]
  - [[#font-and-themes][Font and Themes]]
  - [[#scale][Scale]]
  - [[#lines][Lines]]
  - [[#modeline][Modeline]]
- [[#org-mode][Org-mode]]
  - [[#general-1][General]]
  - [[#agenda][Agenda]]
  - [[#custom-font-faces][Custom font faces]]
  - [[#variable-font-sizes][Variable font sizes]]
  - [[#latex][LaTeX]]
  - [[#org-roam][Org Roam]]
  - [[#tables][Tables]]
  - [[#zen-mode][Zen Mode]]
  - [[#mermaid-diagrams][Mermaid diagrams]]
  - [[#org-roam-ui][Org Roam UI]]
- [[#coding][Coding]]
  - [[#corfu---completion][Corfu - Completion]]
  - [[#rust][Rust]]
  - [[#python][Python]]
- [[#preludes][Preludes]]
  - [[#packagesel][Packages.el]]

* General
** User Information
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
(setq user-full-name "Atri Hegde"
      user-mail-address "atri@example.com")
#+end_src

** Auto save buffers
Auto save all buffers on loss of focus or after 2 seconds idle.
#+begin_src emacs-lisp :tangle packages.el
;;; $DOOMDIR/packages.el -*- lexical-binding: t; no-byte-compile: t -*-
(package! super-save)
#+end_src


#+begin_src emacs-lisp
(after! super-save
  :init
  (setq super-save-auto-save-when-idle t)
  (setq super-save-idle-duration 2)
  (setq super-save-silent t)
  ;; But not for remote files
  (setq super-save-remote-files nil)
  :config
  (super-save-mode +1))

;; super save doesn't work without this...
(after! org
  (super-save-mode +1))
#+end_src

Save files quicker/easier
#+begin_src emacs-lisp
;; Save files quicker/easier
(map! :leader
      :desc "Save Buffer" "SPC" #'save-buffer)
#+end_src

** Tab size
#+begin_src emacs-lisp
;; Tab size
(setq-default tab-width 4)
#+end_src
* User Interface
** Font and Themes
#+begin_src emacs-lisp
(setq doom-theme 'doom-dracula)

;; JetBrains Mono
;; (setq doom-font (font-spec :family "JetBrains Mono" :size 17 :weight 'medium)
;;       doom-variable-pitch-font (font-spec :family "JetBrains Mono" :sie 17 :weight 'medium))
;; Terminess Mono
(setq doom-font (font-spec :family "Terminess Nerd Font Mono" :size 17 :weight 'medium)
      doom-variable-pitch-font (font-spec :family "Terminess Nerd Font Mono" :size 17 :weight 'medium))
#+end_src

** Scale
Turn on big font mode for my HiDPI display
#+begin_src emacs-lisp
;; (when (display-graphic-p)
;;   (doom-big-font-mode t))
#+end_src

** Lines
Custom scroll margin for evil mode.
#+begin_src emacs-lisp
;; Default global scroll margin
(setq-default scroll-margin 7)

;; Apart from these modes which should have a scroll margin of 0
(dolist (mode '(Info-mode term-mode eshell-mode shell-mode erc-mode vterm-mode comint-mode))
  (add-hook (intern (format "%s-hook" mode))
            (lambda () (setq-local scroll-margin 0))))

;; Use relative line numbers
(setq display-line-numbers-type 'relative)
#+end_src

Make evil mode scroll to the next visual line.
#+begin_src emacs-lisp
(evil-global-set-key 'motion "j" 'evil-next-visual-line)
(evil-global-set-key 'motion "k" 'evil-previous-visual-line)
#+end_src

** Modeline
#+begin_src emacs-lisp
(after! doom-modeline
  (display-battery-mode t)
  ;; Also have the file icon
  (setq doom-modeline-major-mode-icon t))
#+end_src

* Org-mode
** General
#+begin_src emacs-lisp
(setq org-directory "~/org/")
#+end_src

** Agenda
#+begin_src emacs-lisp
(setq org-agenda-files '("~/org/roam/agenda/"))
#+end_src

#+begin_src emacs-lisp
(setq org-log-done 'time)
(setq org-hide-emphasis-markers t)
(setq org-startup-with-inline-images t)
(setq org-superstar-headline-bullets-list '("◉" "●" "○" "◆" "●" "○" "◆"))

(after! org
  (add-hook 'org-mode-hook
            (lambda ()
              (setq-local doom-modeline-enable-word-count t))))
#+end_src

** Custom font faces
Keep code-like Org elements aligned by forcing them back to fixed pitch, even when prose uses a variable-pitch face.
#+begin_src emacs-lisp
(after! org
  (add-hook 'org-mode-hook
            (lambda ()
              (face-remap-add-relative 'default :family "Overpass")))
  (set-face-attribute 'org-block nil :family "Terminess Nerd Font Mono")
  (set-face-attribute 'org-block-begin-line nil :family "Terminess Nerd Font Mono")
  (set-face-attribute 'org-block-end-line nil :family "Terminess Nerd Font Mono")
  (set-face-attribute 'org-table nil :inherit 'fixed-pitch)
  (set-face-attribute 'org-formula nil :inherit 'fixed-pitch)
  (set-face-attribute 'org-code nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
  (set-face-attribute 'org-special-keyword nil
                      :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-meta-line nil
                      :inherit '(font-lock-comment-face fixed-pitch))
  (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)
  (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
  (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))
#+end_src

** Variable font sizes
Use a proportional font for Org headings and make higher-level headings stand out without changing the body text size.
#+begin_src emacs-lisp
(after! org
  (dolist (face '((org-level-1 . 1.2)
                  (org-level-2 . 1.1)
                  (org-level-3 . 1.0)
                  (org-level-4 . 1.0)
                  (org-level-5 . 1.0)
                  (org-level-6 . 1.0)
                  (org-level-7 . 1.0)
                  (org-level-8 . 1.0)))
    (set-face-attribute (car face) nil
                        :font "Iosevka Aile"
                        :weight 'medium
                        :height (cdr face)))
  (set-face-attribute 'org-document-title nil
                      :font "Iosevka Aile"
                      :weight 'bold
                      :height 1.3))
#+end_src

** LaTeX
*** Inline $\LaTeX$ previews

#+begin_src emacs-lisp :tangle packages.el
(package! org-fragtog)
#+end_src

#+begin_src emacs-lisp
(after! org
  (add-hook 'org-mode-hook
            #'org-fragtog-mode))
#+end_src

Adjust size of latex previews.
#+begin_src emacs-lisp
(after! org
  (plist-put org-format-latex-options :scale 0.85)
  (setq org-highlight-latex-and-related '(latex))
  (plist-put org-format-latex-options :background "Transparent"))
#+end_src

*** LaTeX export
Keep LaTeX export setup behind Org so it is not loaded during early startup.
The entries in =org-latex-classes= define named export targets for Org's
=#+latex_class:= option. =org-plain-latex= gives a minimal article class that
keeps Org's default package list out of the generated preamble, while =report=
maps Org heading levels onto the LaTeX sectioning commands used by the report
document class.
#+begin_src emacs-lisp
(after! org
  (with-eval-after-load 'ox-latex
    (add-to-list 'org-latex-classes
                 '("org-plain-latex"
                   "\\documentclass{article}
[NO-DEFAULT-PACKAGES]
[PACKAGES]
[EXTRA]"
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                   ("\\paragraph{%s}" . "\\paragraph*{%s}")
                   ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))

  (with-eval-after-load 'ox-latex
    (add-to-list 'org-latex-classes
                 '("report"
                   "\\documentclass{report}"
                   ("\\chapter{%s}" . "\\section*{%s}")
                   ("\\section{%s}" . "\\subsection*{%s}")
                   ("\\subsection{%s}" . "\\subsubsection*{%s}")
                   ("\\subsubsection{%s}" . "\\paragraph*{%s}")
                   ("\\paragraph{%s}" . "\\subparagraph*{%s}"))))

  ;; Use PDF Tools for AUCTeX previews and keep rendered PDFs current.
  (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
        TeX-view-program-list '(("PDF Tools" "TeX-pdf-tools-sync-view"))
        TeX-source-correlate-start-server t)
  (add-hook 'pdf-view-mode-hook #'auto-revert-mode)

  ;; Use minted for source blocks. Requires pygments and shell escape support.
  (setq org-latex-src-block-backend 'minted
        org-latex-packages-alist '(("" "minted"))
        org-latex-pdf-process
        '("pdflatex -shell-escape -interaction nonstopmode -output-directory build %f"))

  (require 'ox-latex))
#+end_src

** Org Roam
#+begin_src emacs-lisp
(after! org-roam
  (setq org-roam-directory (file-truename "~/org/roam/")))
#+end_src

*** Org Roam Daily
#+begin_src emacs-lisp
(after! org-roam
  (setq org-roam-dailies-directory "daily/"
        org-roam-dailies-capture-templates
        '(("d" "default" entry "* %<%H:%M>: %?"
           :ifnew (file+head "%<%Y-%m-%d>.org"
                             "#+title: %<%Y-%m-%d>\n")))))
#+end_src

** Tables
#+begin_src emacs-lisp
(setq org-modern-table-vertical 1)
(setq org-modern-table t)
#+end_src

** Zen Mode
#+begin_src emacs-lisp
(setq +zen-text-scale 0.9)
(setq writeroom-width 100)
(setq writeroom-mode-line t)
#+end_src

** Mermaid diagrams
Get the mermaid packages and intialise them so that I can create mermaid files in org mode.
#+begin_src emacs-lisp :tangle packages.el
(package! mermaid-mode)
(package! ob-mermaid)
#+end_src

#+begin_src emacs-lisp
(use-package! mermaid-mode
  :mode "\\.mmd\\'"
  :config
  (setq mermaid-mmdc-location (or (executable-find "mmdc") "mmdc")
        mermaid-output-format ".svg"))

(use-package! ob-mermaid
  :after org
  :config
  (setq ob-mermaid-cli-path (or (executable-find "mmdc") "mmdc"))
  (setq org-babel-default-header-args:mermaid
        '((:results . "file graphics")
          (:exports . "results")))
  (add-to-list 'org-src-lang-modes '("mermaid" . mermaid))
  (org-babel-do-load-languages
   'org-babel-load-languages
   (append org-babel-load-languages
           '((mermaid . t)))))
#+end_src

** Org Roam UI
#+begin_src emacs-lisp :tangle packages.el
(package! org-roam-ui)
#+end_src
#+begin_src emacs-lisp
(use-package! websocket
  :after org-roam)
(use-package! org-roam-ui
  :after org-roam
  :config
  (setq org-roam-ui-sync-theme t)
  (setq org-roam-ui-follow t)
  (setq org-roam-ui-update-on-save t)
  (setq org-roam-ui-open-on-start t))
#+end_src

* Coding
** Corfu - Completion
Use [[kbd:][RET]] to accept completion
#+begin_src emacs-lisp
;; (after! corfu
;;   (setq corfu-preselect 'first))
;; (setq +corfu-want-ret-to-confirm t)
(after! corfu
     (setq corfu-preselect 'first)
     (map! :map corfu-map
           :gi "TAB" #'corfu-insert
           :gi [tab] #'corfu-insert))
#+end_src

** Rust
Use 4 spaces for tabs.
#+begin_src emacs-lisp
(after! rustic
  (setq-default rustic-indent-offset 4))
#+end_src

Enable clippy
#+begin_src emacs-lisp
;; LSP
;; (after! lsp-rust
;;   (setq lsp-rust-analyzer-cargo-watch-command "clippy"))

;; EGLOT
(after! eglot
  (setq-default eglot-workspace-configuration
                '(:rust-analyzer
                  (:check
                   (:command "clippy")))))
#+end_src

Show latest crate versions in Cargo.toml
#+begin_src emacs-lisp
(add-load-path! "vendor/crates.el")
(require 'crates)

(add-to-list 'auto-mode-alist '("/Cargo\\.toml\\'" . conf-toml-mode))

(defun +doom-enable-crates-mode-maybe ()
  (when (and buffer-file-name
             (string= (file-name-nondirectory buffer-file-name) "Cargo.toml"))
    (crates-mode 1)))

(add-hook 'find-file-hook #'+doom-enable-crates-mode-maybe)
(add-hook 'conf-toml-mode-hook #'+doom-enable-crates-mode-maybe)
(add-hook 'toml-ts-mode-hook #'+doom-enable-crates-mode-maybe)
(add-hook 'toml-mode-hook #'+doom-enable-crates-mode-maybe)

(dolist (buffer (buffer-list))
  (with-current-buffer buffer
    (+doom-enable-crates-mode-maybe)))
#+end_src

** Python
Use =ty= for LSP and =ruff= for formatting
#+begin_src emacs-lisp
(with-eval-after-load 'python
  (set-eglot-client! '(python-mode python-ts-mode) '("ty" "server")))
(with-eval-after-load 'python
  (set-formatter! 'ruff :modes '(python-mode python-ts-mode)))
#+end_src

* Preludes
** Packages.el
#+begin_src emacs-lisp :tangle packages.el
;; To install a package:
;;
;;   1. Declare them here in a `package!' statement,
;;   2. Run 'doom sync' in the shell,
;;   3. Restart Emacs.
;;
;; Use 'C-h f package\!' to look up documentation for the `package!' macro.


;; To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
;; (package! some-package)

;; To install a package directly from a remote git repo, you must specify a
;; `:recipe'. You'll find documentation on what `:recipe' accepts here:
;; https://github.com/radian-software/straight.el#the-recipe-format
;; (package! another-package
;;   :recipe (:host github :repo "username/repo"))

;; If the package you are trying to install does not contain a PACKAGENAME.el
;; file, or is located in a subdirectory of the repo, you'll need to specify
;; `:files' in the `:recipe':
;; (package! this-package
;;   :recipe (:host github :repo "username/repo"
;;            :files ("some-file.el" "src/lisp/*.el")))

;; If you'd like to disable a package included with Doom, you can do so here
;; with the `:disable' property:
;; (package! builtin-package :disable t)

;; You can override the recipe of a built in package without having to specify
;; all the properties for `:recipe'. These will inherit the rest of its recipe
;; from Doom or MELPA/ELPA/Emacsmirror:
;; (package! builtin-package :recipe (:nonrecursive t))
;; (package! builtin-package-2 :recipe (:repo "myfork/package"))

;; Specify a `:branch' to install a package from a particular branch or tag.
;; This is required for some packages whose default branch isn't 'master' (which
;; our package manager can't deal with; see radian-software/straight.el#279)
;; (package! builtin-package :recipe (:branch "develop"))

;; Use `:pin' to specify a particular commit to install.
;; (package! builtin-package :pin "1a2b3c4d5e")


;; Doom's packages are pinned to a specific commit and updated from release to
;; release. The `unpin!' macro allows you to unpin single packages...
;; (unpin! pinned-package)
;; ...or multiple packages
;; (unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
;; (unpin! t)
#+end_src
